version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # UI de administración
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    env_file:
      - ./producer/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3000:3000"    # API REST
    restart: unless-stopped

  consumer:
    build:
      context: ./consumer
    env_file:
      - ./consumer/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
