version: "3.9"

services:
  app:
    build: .
    container_name: node_app
    ports:
      - "3000:3000"
    environment:
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}   
      DB_PORT: ${DB_PORT}  
      DB_USER: ${DB_USER}   
      DB_PASSWORD: ${DB_PASSWORD} 
      DB_NAME: ${DB_NAME}   
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}                   
      MYSQL_USER: ${DB_USER}                       
      MYSQL_PASSWORD: ${DB_PASSWORD}               
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD --silent"]
      interval: 5s
      retries: 10
      timeout: 3s
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:
